title: Open Science Resources
logo: /images/Biohub_Logo_BLK_RGB.png
description: open science for biomedical research
url: https://chanzuckerberg.github.io
baseurl: /open-science

theme: jekyll-theme-minimal
show_sidebar: TRUE

plugins:
  - jekyll-analytics
  - jekyll-sitemap

Plausible:
    domain: 'chanzuckerberg.github.io/open-science'   # The domain configured in plausible
    source: 'https://plausible.io/js/plausible.js' # The source of the javascript
